Complete new payouts - Submit single payouts
bitpay/php-bitpay-client-v2 pull request #68
Opened 2021-11-10 12:37 UTC by nsoni3

This branch has changed for only the submitPayout method with payouts endpoint.

2021-11-12 15:39 UTC, anbugal requested changes

2021-11-12 15:39 UTC, anbugal commented on src/BitPaySDK/Model/Payout/Payout.php
> +    protected $_transactions;
create a model for this object

2021-11-12 15:39 UTC, anbugal commented on src/BitPaySDK/Model/Payout/Payout.php
> +            'transactions'     => $this->getTransactions()
deserialise when created the object with $this->getTransactions()->toArray()

2021-11-15 03:30 UTC, alexstewartja commented
@anbugal Still awaiting your review of #67

2021-11-15 13:36 UTC, merged